As9926 24db
opencomputeproject/OpenNetworkLinux pull request #903
Opened 2022-08-03 03:21 UTC by acctalex

2022-08-03 05:58 UTC, paulmenzel requested changes
Thank you for your patch.

1.  Please document the BMC model in the commit message.
1.  Please fix the typo *interface* in the commit message.
1.  Please describe the problem in the commit message, and why loading the BMC module once is not enough. Why can loading it fail?

2022-08-03 05:58 UTC, paulmenzel commented on packages/platforms/accton/x86-64/as9926-24db/platform-config/r0/src/python/x86_64_accton_as9926_24db_r0/__init__.py
> +INTERVAL = 3
Why these numbers? Please add a comment why it does not work at first try, and why these values were chosen.

2022-08-03 05:58 UTC, paulmenzel commented on packages/platforms/accton/x86-64/as9926-24db/platform-config/r0/src/python/x86_64_accton_as9926_24db_r0/__init__.py
> +    'echo "add,kcs,i/o,0xca2" > /sys/module/ipmi_si/parameters/hotmod']
Should the ] be on the next line?

2022-08-03 05:58 UTC, paulmenzel commented on packages/platforms/accton/x86-64/as9926-24db/platform-config/r0/src/python/x86_64_accton_as9926_24db_r0/__init__.py
> +        status, output = commands.getstatusoutput('ipmitool raw 0x34 0x95')
Please add a comment, what these commands do.

2022-08-03 05:58 UTC, paulmenzel commented on packages/platforms/accton/x86-64/as9926-24db/platform-config/r0/src/python/x86_64_accton_as9926_24db_r0/__init__.py
> +        return True
Please squash the next commit into this one.

2023-09-03 17:28 UTC, sonoble approved these changes
LGTM

2023-09-03 17:29 UTC, merged