Change DEBIAN_MIRROR site to fix build issue
opencomputeproject/OpenNetworkLinux pull request #933
Opened 2023-03-29 02:45 UTC by jonathantsai-qci

https://mirrors.edge.kernel.org/debian/dists/ not support jessie.
Workaround URL is http://archive.debian.org/debian/dists/ and tesk OK.
Please review it. Thank you very much

2023-03-29 03:58 UTC, jonathantsai-qci commented
Re-check again

2023-04-05 12:50 UTC, avs009 requested changes
This is not the best place because it affects all distros.
My recommendation is to change the var ${DEBIAN_MIRROR} directly into the /OpenNetworkLinux/builds/any/rootfs/${DISTRO}/standard/standard.yml file according to the affected distros: Jessie, Stretch and Wheezy.

2023-04-06 11:05 UTC, jonathantsai-qci commented
@avs009 Thanks for your recommendation. Only change distros: Jessie and Wheezy due to https://mirrors.edge.kernel.org/debian/dists/ not include these two distros. Please review again. Thank you very much.

2023-04-10 08:51 UTC, avs009 approved these changes
Changes are ok.

2023-04-24 15:51 UTC, taraschornyiplv approved these changes

2023-06-01 05:04 UTC, paulmenzel commented
Thank you very much for your contribution.

Wouldn’t it be better in line with the current style to adapt `tools/onlrfs.py` and set the string there? Then people could also overwrite it?

Also, there is a small typo in  in the merge/pull request description: “and tesk OK.” → s/tesk/test/

Please also mention both suites *jessy* and *wheezy*.

You could also remove “Please review it. Thank you very much” from the description.

PS: Please note, the future of ONL is unclear.

2023-06-02 03:33 UTC, jonathantsai-qci commented
Stretch also move to http://archive.debian.org/debian/dists/
Notes: Change standard.yml file for wheezy, jessie and stretch

2023-06-08 20:50 UTC, sonoble commented
I have confirmed that it builds and installs, unless there are other issues I will merge it.

2023-06-08 20:53 UTC, sonoble approved these changes

2023-06-12 17:29 UTC, merged